apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: 2017-03-21T07:02:18Z
  generation: 26
  labels:
    app: xxx
  name: test-dc
  namespace: test
  resourceVersion: "80264"
  uid: 52580d49-0e04-11e7-b0fd-02f6bc35da11
spec:
  replicas: 1
  selector:
    app: xxx
    deploymentconfig: test-dc
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: xxx
        deploymentconfig: test-dc
    spec:
      containers:
      - image: 172.30.94.71:5000/test/httpd
        imagePullPolicy: Always
        name: container-1
        terminationMessagePath: /dev/termination-log
      - image: 172.30.94.71:5000/test/httpd
        imagePullPolicy: Always
        name: container-2
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8778
          protocol: TCP
        resources:
          requests:
            cpu: 300m
            memory: 256M
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - container-1
      - container-2
      from:
        kind: ImageStreamTag
        name: httpd:latest
        namespace: test
      lastTriggeredImage: 172.30.94.71:5000/test/httpd
    type: ImageChange
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: 2017-03-22T07:53:07Z
    message: Deployment config has minimum availability.
    status: "True"
    type: Available
  - lastTransitionTime: 2017-03-22T09:34:38Z
    message: Replication controller "radp-services-customer-6" has completed progressing
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  details:
    causes:
    - type: ConfigChange
    message: config change
  latestVersion: 6
  observedGeneration: 26
  replicas: 2
  updatedReplicas: 2

