kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: general-purpose-ssd-gp2
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2 
  zone: ap-southeast-1a
#  iopsPerGB: "10" 
#  encrypted: true 
#  kmsKeyId: keyvalue 

