apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "pv01" 
spec:
  capacity:
    storage: "1Gi" 
  accessModes:
    - "ReadWriteOnce"
  awsElasticBlockStore: 
    fsType: "ext4" 
    volumeID: "vol-03741165d050f24c2" 
